CREATE TABLE KPI_ITEM_DIM_FLAT(
SKU VARCHAR(100),
ITEM_TYPE VARCHAR(30),
BRAND   VARCHAR2(5),
MERCHANDISE_DEPARTMENT VARCHAR(50),
MERCHANDISE_DEPT_NAME  VARCHAR(10),
MERCHANDISE_COLLECTION VARCHAR(50),
MERCHANDISE_COLLECTION_NAME VARCHAR(50),
MERCHANDISE_CLASS VARCHAR(50),
MERCHANDISE_CLASS_NAME VARCHAR(5),
MERCHANDISE_SUBCLASS VARCHAR(50),
MERCHANDISE_SUBCLASS_NAME VARCHAR(10),
KPI_ITEM_SKEY  NUMBER(20,0)
);

INSERT INTO KPI_ITEM_DIM_FLAT(SELECT ID.SKU,ID.TYPE_NAME,ID.BRAND_NAME,IMDD.DESCRIPTION,IMDD.ITEM_MERCHANDISE_DEPARTMENT_NA,
IMCD.DESCRIPTION,IMCD.ITEM_MERCHANDISE_COLLECTION_NA,IMC.DESCRIPTION,
IMC.ITEM_MERCHANDISE_CLASS_NAME,IMSD.DESCRIPTION,IMSD.ITEM_MERCHANDISE_SUBCLASS_NAME,
ID.KPI_DW_SKEY
FROM ITEM_DIM ID
JOIN CLASS_DIM  CD ON ID.KPI_CLASS_SKEY=CD.KPI_DW_SKEY
JOIN ITEM_MERCHANDISE_DEPTARMENT_DIM IMDD ON  IMDD.KPI_DW_SKEY=ID.WS_MERCHANDISE_DEPARTMENT_SKEY
JOIN ITEM_MERCHANDISE_COLLECTION_DIM  IMCD ON IMCD.KPI_DW_SKEY=ID.WS_MERCHANDISE_COLLECTION_SKEY
JOIN ITEM_MERCHANDISE_CLASS_DIM IMC ON IMC.KPI_DW_SKEY=ID.WS_MERCHANDISE_CLASS_SKEY
JOIN ITEM_MERCHANDISE_SUBCLASS_DIM IMSD ON IMSD.KPI_DW_SKEY=ID.WS_MERCHANDISE_SUBCLASS_SKEY
);















 



